# Generated by Django 5.2.3 on 2025-07-24 01:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_paterno', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('escuela', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000, message='El código debe tener 6 dígitos.'), django.core.validators.MaxValueValidator(999999, message='El código debe tener 6 dígitos.')])),
                ('contrasena', models.CharField(blank=True, max_length=100, null=True)),
                ('rol', models.CharField(default='estudiante', max_length=100)),
                ('penalizado', models.BooleanField(default=False)),
                ('penalizacion_motivo', models.TextField(blank=True, null=True)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=9)),
                ('hora', models.CharField(max_length=20)),
                ('cancha', models.CharField(blank=True, max_length=20, null=True)),
                ('deporte', models.CharField(default='voley', max_length=20)),
                ('disponible', models.BooleanField(default=True)),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, null=True)),
                ('cancelacion_confirmada', models.BooleanField(default=False)),
                ('persona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ReservaCanchasUNA.persona')),
                ('reservado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mis_reservas', to='ReservaCanchasUNA.persona')),
            ],
        ),
    ]
