# Generated by Django 5.2.3 on 2025-07-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaCanchasUNA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=9)),
                ('hora', models.CharField(max_length=20)),
                ('cancha', models.CharField(blank=True, max_length=20, null=True)),
                ('deporte', models.CharField(default='voley', max_length=20)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
    ]
