# Generated by Django 5.2.3 on 2025-07-22 14:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaCanchasUNA', '0002_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='codigo',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000, message='El código debe tener 6 dígitos.'), django.core.validators.MaxValueValidator(999999, message='El código debe tener 6 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='rol',
            field=models.CharField(default='estudiante', max_length=100),
        ),
    ]
