# Generated by Django 5.2.3 on 2025-07-23 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaCanchasUNA', '0003_alter_persona_codigo_alter_persona_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='confirmada',
            field=models.BooleanField(default=False),
        ),
    ]
