# Generated by Django 5.2.3 on 2025-07-23 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaCanchasUNA', '0003_alter_persona_codigo_alter_persona_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='penalizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='codigo',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000, message='El código debe tener 6 dígitos.'), django.core.validators.MaxValueValidator(999999, message='El código debe tener 6 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
