# Generated by Django 5.2.3 on 2025-07-23 01:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaCanchasUNA', '0004_reserva_confirmada'),
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='estudiante',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiante.estudiante'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='codigo',
            field=models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(100000, message='El código debe tener 6 dígitos.'), django.core.validators.MaxValueValidator(999999, message='El código debe tener 6 dígitos.')]),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
