# Generated by Django 5.2.3 on 2025-07-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaCanchasUNA', '0004_persona_penalizado_alter_persona_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='penalizacion_motivo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
