# Generated by Django 5.2.3 on 2025-07-23 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaCanchasUNA', '0004_alter_persona_codigo_alter_persona_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ReservaCanchasUNA.persona'),
        ),
    ]
