# Generated by Django 5.2.3 on 2025-07-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaCanchasUNA', '0005_persona_penalizacion_motivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
