# Generated by Django 5.2.3 on 2025-07-24 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaCanchasUNA', '0005_reserva_estudiante_alter_persona_codigo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='confirmada',
            new_name='cancelacion_confirmada',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='estudiante',
        ),
    ]
