# Generated by Django 5.2.3 on 2025-07-23 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaCanchasUNA', '0006_persona_fecha_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='reservado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mis_reservas', to='ReservaCanchasUNA.persona'),
        ),
    ]
