# Generated by Django 5.2.3 on 2025-07-24 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReservaCanchasUNA', '0006_rename_confirmada_reserva_cancelacion_confirmada_and_more'),
        ('estudiante', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estudiante',
        ),
    ]
